### ISSUE TITLE
problem retrieving data

### ISSUE THREAD

**Issue by kobezt08** [Fosome/garb#14] opened 2009-10-26 09:47 UTC
Hi, 

I'm new to the usage of gard in ror. Currently I'm having some problem getting the data from GA as the openstruct returns a empty table,

My code is:

class AnalyticsController < ApplicationController
  include Garb
 def index
    Session.login('xxx', 'xxx')
    @profile = Profile.all.detect{|p| p.table_id == 'xxxxx'.to_ga} 
    @results = Hits.results(@profile)# do

   end
 end

class Hits
  include Garb::Resource
  metrics :pageviews
  dimensions :pagepath
end
## When printing out as <% debug @results %> here is what i get
- !ruby/object:OpenStruct 
  table: {}
- !ruby/object:OpenStruct 
  table: {}
- !ruby/object:OpenStruct 
  table: {}
- !ruby/object:OpenStruct 
  table: {}

I'm not very sure which part went wrong, but hope someone can give me some guidance. Could it be something to do with the namespace issue?

**Comment by tpitale** [comment] 2009-10-26 14:24
Can you link to a gist (http://gist.github.com)? The code you pasted isn't well-formatted in Issues.

**Comment by kobezt08** [comment] 2009-10-26 17:40
my apology. Here's the code @ gist http://gist.github.com/218728

**Comment by zackchandler** [comment] 2009-10-26 18:04
I'm having the exact same problem using a simple test report:

http://gist.github.com/218875

**Comment by tpitale** [comment] 2009-10-26 18:37
I ran through my own demo scripts, and this is being caused by a namespace issue. It appears that google has changed the namespace in the XML returned from the API. However, this was unannounced and did not seem to happen for everyone at once.

This namespace problem is catalogued in another issue, so I'm closing this one and will fix the issue ASAP.

**Closed as completed by tpitale** 2009-10-26 18:37 UTC

**Comment by zackchandler** [comment] 2009-10-26 19:09
awesome!

**Comment by kobezt08** [comment] 2009-10-27 01:14
thanks =)
